import type { Tool } from "./types";

export const TOOLS: Tool[] = [
  // ── Guest Tools ──
  {
    slug: "trip-cost-calculator",
    name: "Villa Holiday Budget Planner",
    tagline: "Plan your Greece villa holiday budget with clarity",
    description: "Estimate your total trip costs across 12 Greek destinations — accommodation, flights, dining, activities, transfers, and car rental. Seasonal pricing adjustments and group size support included.",
    category: "planning",
    status: "comingSoon",
    roles: ["guest"],
    primaryRole: "guest",
    color: "cyan",
    hasDemo: false,
    features: ["12 destinations with seasonal pricing", "Accommodation + flights + dining + activities", "Car rental estimates", "Group size adjustment", "Currency conversion"],
  },
  {
    slug: "itinerary-builder",
    name: "Villa Holiday Itinerary Planner",
    tagline: "Build a day-by-day itinerary around your villa destination",
    description: "Create a personalised Greece itinerary. Select destinations, set your travel pace, choose interests, and generate a curated day-by-day plan to complement your villa stay.",
    category: "planning",
    status: "active",
    roles: ["guest"],
    primaryRole: "guest",
    color: "cyan",
    hasDemo: true,
    features: ["12 Greek destinations", "Customisable days per stop", "8 interest categories", "3 travel pace options", "Group type selection", "Copy-to-clipboard itinerary"],
  },
  {
    slug: "property-comparison",
    name: "Villa Comparison Tool",
    tagline: "Compare shortlisted villas side-by-side",
    description: "Select up to 4 properties and compare them on nightly rate, size, bedrooms, amenities, and guest rating. A quick verdict highlights the best value, highest rated, and most spacious option.",
    category: "planning",
    status: "active",
    roles: ["guest"],
    primaryRole: "guest",
    color: "blue",
    hasDemo: true,
    features: ["Compare up to 4 villas", "Feature-by-feature table", "Amenity checklist", "Price per m² calculation", "Quick verdict summary"],
  },
  {
    slug: "events-calendar",
    name: "Greek Events & Festivals Calendar",
    tagline: "Discover what's happening during your stay",
    description: "Browse 30+ Greek events across 2026 — national holidays, cultural festivals, music events, food celebrations, and sporting events. Filter by month, region, and type to time your trip perfectly.",
    category: "planning",
    status: "active",
    roles: ["guest", "owner"],
    primaryRole: "guest",
    color: "amber",
    hasDemo: true,
    features: ["30+ events across 2026", "Filter by month, region, type", "8 event categories", "Impact rating for pricing guidance", "Pricing tips for owners"],
  },
  {
    slug: "ferry-island-planner",
    name: "Ferry & Island-Hopping Planner",
    tagline: "Plan island-hopping around your villa stay",
    description: "Plan multi-island trips across 18 Greek islands with ferry routes, seasonal pricing, and total trip budgets. Ideal for guests extending their villa holiday with island exploration.",
    category: "planning",
    status: "comingSoon",
    roles: ["guest"],
    primaryRole: "guest",
    color: "blue",
    hasDemo: false,
    features: ["18 islands, 5 departure ports", "Seasonal ferry pricing", "Inter-island routes", "Trip budget breakdown"],
  },

  // ── Owner Tools ──
  {
    slug: "vacation-owner-calculator",
    name: "Villa Revenue Calculator",
    tagline: "See what your villa could earn — with full cost transparency",
    description: "Research-backed calculator for Greek villa owners. Covers 50 destinations with real market data: seasonal revenue projections, all operating expenses, management fee comparison, 2026 Greek tax calculations (individual and corporate), net profit, and yield analysis.",
    category: "revenue",
    status: "active",
    roles: ["owner"],
    primaryRole: "owner",
    color: "emerald",
    hasDemo: true,
    features: [
      "50 Greek destinations with real ADR & occupancy data",
      "7 property types (apartment to luxury villa)",
      "5 management models compared",
      "2026 Greek tax scales (individual 15–45% & corporate 22%+5%)",
      "Full expense breakdown (13 cost items)",
      "Seasonal pricing engine",
      "Net yield / ROI calculation",
      "Individual vs company ownership comparison",
    ],
    useCases: [
      { role: "Villa Owners", cases: ["Estimate net rental income", "Compare self-management vs professional management", "Understand tax implications", "Plan investment ROI"] },
    ],
    inputs: ["Region", "Property type & size", "Management model", "Ownership type", "Custom nightly rate"],
    outputs: ["Gross revenue", "Full expense breakdown", "Tax calculation", "Net profit", "Monthly income", "Net yield"],
  },
  {
    slug: "rental-income-estimator",
    name: "Quick Income Estimator",
    tagline: "Get a quick estimate of your villa's rental potential",
    description: "A lighter, faster version of the full calculator. Enter your region, property type, and get an instant income range with occupancy and rate benchmarks.",
    category: "revenue",
    status: "comingSoon",
    roles: ["owner"],
    primaryRole: "owner",
    color: "emerald",
    hasDemo: false,
    features: ["12 regions", "Instant income range", "Occupancy benchmarks", "3-year projection"],
  },
  {
    slug: "occupancy-heatmap",
    name: "Seasonal Demand Heatmap",
    tagline: "Understand your region's demand patterns",
    description: "Visual monthly heatmap showing occupancy trends across Greek regions. Identify peak months, shoulder opportunities, and off-season gaps to optimise your pricing strategy.",
    category: "analytics",
    status: "comingSoon",
    roles: ["owner", "pmc"],
    primaryRole: "owner",
    color: "violet",
    hasDemo: false,
    features: ["12 regions", "Monthly heatmap", "Pricing suggestions", "Gap analysis"],
  },
  {
    slug: "expense-tracker",
    name: "Villa Expense Tracker",
    tagline: "Track your villa's operating costs clearly",
    description: "Log and categorise all property expenses — cleaning, maintenance, utilities, insurance, and more. Multi-property support with tax deduction insights and net profit calculations.",
    category: "operations",
    status: "comingSoon",
    roles: ["owner"],
    primaryRole: "owner",
    color: "slate",
    hasDemo: false,
    features: ["11 expense categories", "Multi-property support", "Tax deductions", "Net profit calculation"],
  },
  {
    slug: "review-response-generator",
    name: "Guest Review Response Assistant",
    tagline: "Respond to guest reviews professionally and quickly",
    description: "Generate thoughtful, on-brand responses to guest reviews. Choose sentiment, tone, and highlight specific praise or issues. Copy-ready responses that maintain your villa's reputation.",
    category: "operations",
    status: "comingSoon",
    roles: ["owner", "pmc"],
    primaryRole: "owner",
    color: "pink",
    hasDemo: false,
    features: ["3 sentiments × 4 tones", "Praise/issue tags", "Copy to clipboard", "Brand-consistent language"],
  },

  // ── Partner Tools ──
  {
    slug: "commission-calculator",
    name: "Agent Commission Calculator",
    tagline: "See your earning potential as a Villa4you partner agent",
    description: "Calculate projected earnings across 5 commission tiers with property type adjustments and tier progression tracking. Understand exactly how the partner model rewards performance.",
    category: "revenue",
    status: "comingSoon",
    roles: ["agent"],
    primaryRole: "agent",
    color: "blue",
    hasDemo: false,
    features: ["5 commission tiers", "Property type adjustments", "Tier progression tracking", "Monthly/annual projections"],
  },
  {
    slug: "investment-analyzer",
    name: "Property Investment Analyzer",
    tagline: "Evaluate Greek property investments with structured data",
    description: "Analyse ROI, break-even timeline, and mortgage scenarios across 11 Greek regions. Built for agents advising clients on villa investment decisions.",
    category: "analytics",
    status: "comingSoon",
    roles: ["agent", "owner"],
    primaryRole: "agent",
    color: "indigo",
    hasDemo: false,
    features: ["11 regions", "ROI calculation", "Break-even analysis", "Mortgage scenario modelling"],
  },
  {
    slug: "contract-generator",
    name: "Greek Lease & Contract Generator",
    tagline: "Generate Greek-compliant rental agreements",
    description: "Create structured lease agreements for 4 Greek contract types with required and optional clauses. Built for PMCs and property managers who need reliable legal templates.",
    category: "operations",
    status: "comingSoon",
    roles: ["pmc"],
    primaryRole: "pmc",
    color: "slate",
    hasDemo: false,
    features: ["4 Greek contract types", "Required/optional clauses", "Preview mode", "Download-ready"],
  },
  {
    slug: "golden-visa-calculator",
    name: "Golden Visa Investment Calculator",
    tagline: "Evaluate Greek Golden Visa property requirements",
    description: "Calculate investment thresholds, acquisition costs, rental income projections, and ROI across 15 Greek zones. Essential for agents working with foreign investors.",
    category: "revenue",
    status: "comingSoon",
    roles: ["agent", "owner"],
    primaryRole: "agent",
    color: "amber",
    hasDemo: false,
    features: ["15 zones with 3 thresholds", "Acquisition cost breakdown", "Rental income projection", "Family cost per member"],
  },
  {
    slug: "guest-guidebook",
    name: "Digital Guest Guidebook Builder",
    tagline: "Create a branded guidebook for your villa guests",
    description: "Build a professional digital guidebook with 14 sections, 6 languages, and 4 visual themes. Include house rules, local tips, emergency contacts, and area recommendations.",
    category: "operations",
    status: "comingSoon",
    roles: ["owner", "pmc"],
    primaryRole: "pmc",
    color: "teal",
    hasDemo: false,
    features: ["14 guidebook sections", "6 languages", "4 visual themes", "Phone preview mockup"],
  },
];

export const TOOL_CATEGORIES = [
  { slug: "planning", label: "Trip Planning", icon: "map" },
  { slug: "revenue", label: "Revenue & Investment", icon: "chart" },
  { slug: "operations", label: "Operations", icon: "cog" },
  { slug: "analytics", label: "Analytics & Insights", icon: "bar-chart" },
  { slug: "collaboration", label: "Collaboration", icon: "users" },
] as const;

export const TOOL_ROLES = [
  { slug: "guest", label: "Guests" },
  { slug: "owner", label: "Villa Owners" },
  { slug: "agent", label: "Agents" },
  { slug: "pmc", label: "Property Managers" },
  { slug: "serviceProvider", label: "Service Providers" },
] as const;
